force-app/main/default/objects/Account/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <description>Cep do endereço principal da conta.</description>
    <label>CEP</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnderecoCompletoSemNumero__c.field-meta.xml
<CustomField>
    <fullName>EnderecoCompletoSemNumero__c</fullName>
    <label>Endereço Completo Sem Número</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnderecoEstado__c.field-meta.xml
<CustomField>
    <fullName>EnderecoEstado__c</fullName>
    <inlineHelpText>Informe a UF do endereço principal da conta.</inlineHelpText>
    <label>Estado do Endereço</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EstadosFederacao</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EnderecoNumero__c.field-meta.xml
<CustomField>
    <fullName>EnderecoNumero__c</fullName>
    <inlineHelpText>Número do Endereço.</inlineHelpText>
    <label>Número do Endereço</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QualificacaoCliente__c.field-meta.xml
<CustomField>
    <fullName>QualificacaoCliente__c</fullName>
    <label>Qualificação do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QualificacaoCliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <description>Campo autoincremento para teste de Trigger - Bootcamp 7</description>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendedor__c/Vendedor__c.object-meta.xml
<CustomObject>
    <label>Vendedor</label>
    <nameField>
        <label>Vendedor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/selector/AccountsSelector.cls
public inherited sharing class AccountsSelector extends fflib_SObjectSelector {
    
    public Schema.SObjectType getSObjectType(){
        return Account.sObjectType;
    }
   
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Account.Id,
            Account.Name,
            Account.Vendedor__c,
            Account.QualificacaoCliente__c,
            Account.CEP__c,
            Account.EnderecoCompletoSemNumero__c,
            Account.EnderecoNumero__c,
            Account.EnderecoEstado__c
        };
    }

    public Integer getMaxValueForQuantityField(){
        AggregateResult[] res = [SELECT MAX(Quantidade__c) quantidade FROM Account];
        return (res.get(0).get('quantidade') == null) ? 0 : Integer.valueOf(res.get(0).get('quantidade'));
    }

    public List<Account> selectAll(){
		return (List<Account>) Database.query(
			newQueryFactory().
            selectField(Account.Id).
            selectField(Account.Name).
            selectField(Account.Vendedor__c).
            selectField(Account.QualificacaoCliente__c).
            selectField(Account.CEP__c).
            selectField(Account.EnderecoCompletoSemNumero__c).
            selectField(Account.EnderecoNumero__c).
            selectField(Account.EnderecoEstado__c).
            toSOQL()
		);
    }

    public List<Account> selectByIds(Set<Id> accIds){
		return (List<Account>) Database.query(
			newQueryFactory().
            selectField(Account.Id).
            selectField(Account.Name).
            selectField(Account.Vendedor__c).
            selectField(Account.QualificacaoCliente__c).
            selectField(Account.CEP__c).
            selectField(Account.EnderecoCompletoSemNumero__c).
            selectField(Account.EnderecoNumero__c).
            selectField(Account.EnderecoEstado__c).
            setCondition('Id IN : accIds').
            toSOQL()
		);		
        //return (List<Account>) selectSObjectsById(accIds);        
    }

    public Account selectById(Id accId){
        Set<Id> ids = new Set<Id>();
        ids.add(accId);
        List<Account> accs = selectByIds(ids);
        if (accs.size() == 1) {return accs.get(0);} else {return null;}
    }

    public List<Account> selectAllWithoutEndereco(){
        return (List<Account>) Database.query(
			newQueryFactory().
            selectField(Account.Id).
            selectField(Account.Name).
            selectField(Account.Vendedor__c).
            selectField(Account.QualificacaoCliente__c).
            selectField(Account.CEP__c).
            selectField(Account.EnderecoCompletoSemNumero__c).
            selectField(Account.EnderecoNumero__c).
            selectField(Account.EnderecoEstado__c).
            setCondition('CEP__c is not null and EnderecoCompletoSemNumero__c is null').
            toSOQL()
		);       
    }

}