force-app/main/default/objects/Account/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <description>Cep do endereço principal da conta.</description>
    <label>CEP</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnderecoCompletoSemNumero__c.field-meta.xml
<CustomField>
    <fullName>EnderecoCompletoSemNumero__c</fullName>
    <label>Endereço Completo Sem Número</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QualificacaoCliente__c.field-meta.xml
<CustomField>
    <fullName>QualificacaoCliente__c</fullName>
    <label>Qualificação do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QualificacaoCliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendedor__c/Vendedor__c.object-meta.xml
<CustomObject>
    <label>Vendedor</label>
    <nameField>
        <label>Vendedor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendedor__c/recordTypes/Externo.recordType-meta.xml
<RecordType>
    <fullName>Externo</fullName>
    <active>true</active>
    <description>Se o vendedor trabalha externamente na organização.</description>
    <label>Externo</label>
</RecordType>

force-app/main/default/objects/Vendedor__c/recordTypes/Interno.recordType-meta.xml
<RecordType>
    <fullName>Interno</fullName>
    <active>true</active>
    <description>Se o vendedor trabalha internamente na organização.</description>
    <label>Interno</label>
</RecordType>

force-app/main/default/classes/service/AccountsService.cls
public with sharing class AccountsService {
    
    public static void setAddressForAccount(Set<Id> recordIds){

        fflib_ISObjectDomain objectDomain = (fflib_ISObjectDomain) Application.domain.newInstance(recordIds);
        fflib_ISObjectSelector objectSelector = Application.selector.newInstance(Account.SObjectType);
		fflib_ISObjectUnitOfWork unitOfWork = Application.UOW.newInstance();
        
        // Lista de contas para obter o CEP
        List<Account> accs = objectSelector.selectSObjectsById(recordIds);

        // Map de endereços
        Map<Id, AddressClient.AddressResponse> mapAddress = new Map<Id, AddressClient.AddressResponse>();

        // Client HTTP que busca o endereço por WS
        AddressClient addressClient1 = ViaCepAddressClient.create();

        for (Account acc : accs){
            if(String.isBlank(acc.CEP__c) | !String.isBlank(acc.EnderecoCompletoSemNumero__c)){
                System.debug('Account CEP isBlank -> ' + acc.Id);
                mapAddress.put(acc.Id, null);
            } else {
                AddressClient.AddressResponse result = addressClient1.getAddress(acc.CEP__c);
                System.debug('Account CEP return -> ' + result.cep + ' for ' + acc.Id);
                mapAddress.put(acc.Id, result);
            }
        }

        Accounts domainAccount = (Accounts) objectDomain;
        domainAccount.setAddress(mapAddress, unitOfWork);

		try{
			unitOfWork.commitWork();
		}
		catch(Exception e){
			throw e;
		}        
    }

    private enum TipoVendedor {
        INTERNO,
        EXTERNO,
        AMBOS    
    }

    private static TipoVendedor converterTipoVendedor(String tp){
        return (tp == 'Interno') ? TipoVendedor.INTERNO : TipoVendedor.EXTERNO;
    }

    private static TipoVendedor converterQualificacaoCliente(String qualificacao){
        if (qualificacao == 'Prata'){
            return TipoVendedor.AMBOS;
        } else if (qualificacao == 'Bronze'){
            return TipoVendedor.EXTERNO;
        }
        return TipoVendedor.INTERNO;
    }

    public static void setDefaultVendedorForAccount(Set<Id> recordIds){

        Integer maxQuantidadeContas;
    
        fflib_ISObjectDomain objectDomain = (fflib_ISObjectDomain) Application.domain.newInstance(recordIds);        
        AccountsSelector accSelector = (AccountsSelector) Application.selector.newInstance(Account.SObjectType);
        VendedoresSelector vendedorSelector = (VendedoresSelector) Application.selector.newInstance(Vendedor__c.sObjectType); 
        fflib_ISObjectUnitOfWork unitOfWork = Application.UOW.newInstance();
        List<Vendedor__c> vendedores = vendedorSelector.selectAllWithAccounts();
        List<Account> accs = accSelector.selectByIds(recordIds);

        // Map de Vendedores que serão atualizados nas contas
        Map<Id, Id> mapVendedor = new Map<Id, Id>();

        for (Account acc : accs){
            if (acc.Vendedor__c == null){
                Integer menorQuantidadeContas = 2147483647; // max positive value 
                Integer idxVendedor = null;        
                TipoVendedor tp = converterQualificacaoCliente(acc.QualificacaoCliente__c);
                for (Vendedor__c vendedor : vendedores){                        
                    if ((converterTipoVendedor(vendedor.RecordType.Name) == tp) | (tp == TipoVendedor.AMBOS)){
                        if (vendedor.Accounts__r.size() < menorQuantidadeContas){
                            menorQuantidadeContas = vendedor.Accounts__r.size();
                            idxVendedor = vendedores.indexOf(vendedor);                    
                        }    
                    }
                }                          
                if (idxVendedor != null){
                    vendedores.get(idxVendedor).Accounts__r.add(acc);
                    mapVendedor.put(acc.Id, vendedores.get(idxVendedor).Id);
                } else {
                    mapVendedor.put(acc.Id, null);
                }        
            } else {
                mapVendedor.put(acc.Id, null); // keep default
            }
        }
        
        Accounts domainAccount = (Accounts) objectDomain;
        domainAccount.setDefaultVendedor(mapVendedor, unitOfWork);

		try{
			unitOfWork.commitWork();
		}
		catch(Exception e){
			throw e;
		}               
    }

    public static void setAddressForAllAccount(){
        AccountsSelector accSelector = (AccountsSelector) Application.selector.newInstance(Account.SObjectType);
        Set<Id> recordIds = new Set<Id>();
        for (Account acc : accSelector.selectAllWithoutEndereco()){
            recordIds.add(acc.Id);
        }
        setAddressForAccount(recordIds); 
    }
}    