force-app/main/default/objects/Account/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <description>Cep do endereço principal da conta.</description>
    <label>CEP</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnderecoCompletoSemNumero__c.field-meta.xml
<CustomField>
    <fullName>EnderecoCompletoSemNumero__c</fullName>
    <label>Endereço Completo Sem Número</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnderecoEstado__c.field-meta.xml
<CustomField>
    <fullName>EnderecoEstado__c</fullName>
    <inlineHelpText>Informe a UF do endereço principal da conta.</inlineHelpText>
    <label>Estado do Endereço</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EstadosFederacao</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendedor__c/Vendedor__c.object-meta.xml
<CustomObject>
    <label>Vendedor</label>
    <nameField>
        <label>Vendedor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/domain/Accounts.cls
public class Accounts extends fflib_SObjectDomain {

    public Accounts(List<Account> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Accounts(sObjectList);
        }
    }
    
    public void setAddress(Map<Id, AddressClient.AddressResponse> addresses, fflib_ISObjectUnitOfWork unitOfWork){
        
        System.debug('setAddress -> Accounts ' + Records.size());
        if (addresses.keySet().size() != Records.size()) {
            throw new AccountException('A quantidade de endereços não corresponde com a quantidade de contas.');
        }

        for(Account acc : (List<Account>) Records) {
            AddressClient.AddressResponse address = addresses.get(acc.Id);
            if (address != null){
                System.debug('setAddress -> ' + acc.Id + ' -> ' + address.logradouro);
                acc.EnderecoCompletoSemNumero__c = address.logradouro + ', ' + address.bairro + ', ' + address.localidade;
                acc.EnderecoEstado__c = address.uf;
            } else {
                System.debug('setAddress -> address not found for ' + acc.Id);
                acc.CEP__c.addError('Não localizado ou não disponível a consulta de CEP para: ' + acc.CEP__c);
            }                
        }

        unitOfWork.registerDirty((List<Account>) Records);
    }

    public void setDefaultVendedor(Map<Id, Id> vendedores, fflib_ISObjectUnitOfWork unitOfWork){

        if (vendedores.keySet().size() != Records.size()) {
            throw new AccountException('A quantidade de vendedores não corresponde com a quantidade de contas.');
        }

        for(Account acc : (List<Account>) Records) {
            if(acc.Vendedor__c == null) {
                Id idVendedor = vendedores.get(acc.Id);
                if (idVendedor != null){
                    acc.Vendedor__c = idVendedor;
                } else {
                    acc.Vendedor__c.addError('Não foi localizado nenhum vendedor padrão para esta conta.');
                }                
            }
        }

        unitOfWork.registerDirty((List<Account>) Records);
    }    
    
    public class AccountException extends Exception {}
}