force-app/main/default/objects/Account/fields/QualificacaoCliente__c.field-meta.xml
<CustomField>
    <fullName>QualificacaoCliente__c</fullName>
    <label>Qualificação do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QualificacaoCliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendedor__c/Vendedor__c.object-meta.xml
<CustomObject>
    <label>Vendedor</label>
    <nameField>
        <label>Vendedor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/selector/VendedoresSelector.cls
public inherited sharing class VendedoresSelector extends fflib_SObjectSelector {
    
    public Schema.SObjectType getSObjectType(){
        return Vendedor__c.sObjectType;
    }
   
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Vendedor__c.Id,
            Vendedor__c.Name
        };
    }

    public List<Vendedor__c> selectAll(){
        /*
        fflib_QueryFactory query = newQueryFactory();           
        //query.setCondition('Name IN :names');
        return (List<Vendedor__c>) Database.query( query.toSOQL() );        
        */
        return [SELECT Id, Name, RecordType.Name FROM Vendedor__c];
    }

    public List<Vendedor__c> selectAllWithAccounts(){
        /*
        fflib_QueryFactory query = newQueryFactory();           
        //query.setCondition('Name IN :names');
        return (List<Vendedor__c>) Database.query( query.toSOQL() );        
        */
        return [SELECT Id, Name, RecordType.Name, (SELECT Id, Name, QualificacaoCliente__c FROM Accounts__r) FROM Vendedor__c];
    }

}